(function (root) {
  'use strict';
  const D = root.DiagramData;
  function createState() {
    return {
      project: Object.fromEntries(D.questions.map(q => [q.id, q.options?.some(o => typeof o.value === 'boolean') ? null : ''])),
      organizations: Object.fromEntries(D.organizations.map(o => [o.id, { ...o, name: '', member: false, visible: false }])),
      edges: [],
      autoEdgeOverrides: {},
      ui: { currentSection: 0, showAllQuestions: false, connectionMode: null, invalidNumbers: {} }
    };
  }
  function visibleOrganizations(state) {
    return D.organizations.map(o => state.organizations[o.id]).filter(o => o.visible && o.name.trim() && o.lane);
  }
  function buildDiagramTitle(state) {
    const p = state.project;
    const contribution = p.contributionOrganization.trim();
    return `${p.orderType}${p.caseType}${contribution ? `（${contribution}）` : ''}`;
  }
  function autoEdges(state) {
    const nodes = visibleOrganizations(state).filter(o => o.lane === 'middle');
    return nodes.slice(1).map((o, i) => {
      const id = `auto-${nodes[i].id}-${o.id}`;
      return { id, from: nodes[i].id, to: o.id, type: 'black-solid', labelType: 'none', label: '', ...state.autoEdgeOverrides[id], autoGenerated: true };
    }).filter(e => !e.deleted);
  }
  function visibleEdges(state) {
    const ids = new Set(['g', ...visibleOrganizations(state).map(o => o.id)]);
    return [...autoEdges(state), ...state.edges.filter(e => ids.has(e.from) && ids.has(e.to))];
  }
  function isOwnerContractor(from, to) { return [from, to].sort().join('|') === 'org1|org2'; }
  function edgeError(state, edge) {
    const ids = new Set(['g', ...visibleOrganizations(state).map(o => o.id)]);
    if (!ids.has(edge.from) || !ids.has(edge.to)) return '表示中の組織を選択してください。';
    if (edge.from === edge.to) return '同じ組織には接続できません。';
    const type = D.edgeTypes.find(t => t.id === edge.type);
    if (!type) return '線種を選択してください。';
    // 矢印は同じ組織間・同じ線種・同じラベルでも複数登録できる。
    // 無方向の線だけは完全重複になって区別できないため、従来どおり拒否する。
    if (!type.arrow && visibleEdges(state).some(e => (!edge.id || e.id !== edge.id) && e.type === edge.type && e.label === edge.label && ((e.from === edge.from && e.to === edge.to) || (e.from === edge.to && e.to === edge.from)))) return '同じ組織間に、同じ線種・ラベルの線があります。';
    return '';
  }
  function resolveLabel(typeId, labelId, extra) {
    if (labelId === 'none') return '';
    const def = D.edgeTypes.find(t => t.id === typeId)?.labels.find(l => l.id === labelId);
    if (!def) throw new Error('ラベルを選択してください。');
    if (!def.extra) return def.id === 'none' ? '' : def.text;
    const value = extra.trim();
    if (!value) return '';
    if (def.extra === 'percent' && (!/^\d+(\.\d+)?$/.test(value) || Number(value) > 100)) throw new Error('割合は0〜100の数値で入力してください。');
    return def.id === 'custom' ? value : def.text.replace('●', value);
  }
  function putEdge(state, edge) {
    if (edge.autoGenerated) state.autoEdgeOverrides[edge.id] = { ...edge };
    else {
      const index = state.edges.findIndex(e => e.id === edge.id);
      if (index < 0) state.edges.push(edge); else state.edges[index] = edge;
    }
  }
  function saveEdge(state, edge, { applyRelations = visibleEdges(state).some(e => e.id === edge.id) } = {}) {
    const error = edgeError(state, edge);
    if (error) throw new Error(error);
    // 編集と連動変更をまとめて検証し、途中まで保存されることを防ぐ。
    const draft = { ...state, edges: state.edges.map(e => ({ ...e })), autoEdgeOverrides: { ...state.autoEdgeOverrides } };
    putEdge(draft, edge);
    if (applyRelations) {
      const materials = { 'material-work': '材工', material: '材', work: '工' };
      const key = edge.type === 'black-solid' ? edge.labelType : edge.type === 'red-dashed-arrow' ? edge.labelType.replace(/^estimate-/, '') : '';
      const material = materials[key];
      const samePair = e => [e.from, e.to].sort().join('|') === [edge.from, edge.to].sort().join('|');
      if (material && edge.label) {
        const targetType = edge.type === 'black-solid' ? 'red-dashed-arrow' : 'black-solid';
        const blankTargets = visibleEdges(draft).filter(e => e.id !== edge.id && samePair(e) && e.type === targetType && !e.label.trim());
        for (const other of blankTargets) {
          putEdge(draft, { ...other, label: targetType === 'black-solid' ? material : `見積（${material}）`, labelType: targetType === 'black-solid' ? key : `estimate-${key}`, labelExtra: '' });
        }
        if (edge.type === 'black-solid' && !blankTargets.length) {
          const laneOf = id => id === 'g' ? 'upper' : draft.organizations[id]?.lane;
          const middleIds = D.organizations.filter(o => o.lane === 'middle').map(o => o.id);
          const [fromLane, toLane] = [laneOf(edge.from), laneOf(edge.to)];
          let estimateFrom = edge.from, estimateTo = edge.to;
          if (fromLane === 'middle' && toLane === 'middle') {
            [estimateFrom, estimateTo] = middleIds.indexOf(edge.from) > middleIds.indexOf(edge.to) ? [edge.from, edge.to] : [edge.to, edge.from];
          } else if (fromLane !== toLane && [fromLane, toLane].includes('middle') && [fromLane, toLane].includes('upper')) {
            [estimateFrom, estimateTo] = fromLane === 'upper' ? [edge.from, edge.to] : [edge.to, edge.from];
          }
          const suffix = `${Date.now()}-${Math.random().toString(36).slice(2, 9)}`;
          putEdge(draft, { id: `edge-estimate-${suffix}`, from: estimateFrom, to: estimateTo, type: 'red-dashed-arrow', labelType: `estimate-${key}`, label: `見積（${material}）`, labelExtra: '', autoGenerated: false });
          putEdge(draft, { id: `edge-payment-${suffix}`, from: estimateTo, to: estimateFrom, type: 'red-solid-arrow', labelType: 'none', label: '', autoGenerated: false });
        }
        if (edge.type === 'red-dashed-arrow' && !visibleEdges(draft).some(e => samePair(e) && e.type === 'red-solid-arrow' && !e.label.trim())) {
          putEdge(draft, { id: `edge-payment-${Date.now()}-${Math.random().toString(36).slice(2, 9)}`, from: edge.to, to: edge.from, type: 'red-solid-arrow', labelType: 'none', label: '', autoGenerated: false });
        }
      }
    }
    for (const candidate of visibleEdges(draft)) {
      const conflict = edgeError(draft, candidate);
      if (conflict) throw new Error(conflict);
    }
    state.edges = draft.edges; state.autoEdgeOverrides = draft.autoEdgeOverrides;
  }
  function removeEdge(state, edge) {
    if (edge.autoGenerated) state.autoEdgeOverrides[edge.id] = { deleted: true };
    else state.edges = state.edges.filter(e => e.id !== edge.id);
  }
  root.DiagramModel = { createState, visibleOrganizations, buildDiagramTitle, autoEdges, visibleEdges, edgeError, resolveLabel, isOwnerContractor, saveEdge, removeEdge };
})(globalThis);
